#!/usr/bin/Rscript

# Run this script after you have finished CIBERSORT's “Impute Cell Fractions” module and running TMECircDB_featureCounts_sum.r

# Pre-requisites
library(nnls)
library(arm)

# Change this to your working directory
# This directory should contain the CIBERSORT estimated cell type composition file
setwd('current_directory')

# Import sample info
# Sample info file should have the following columns: sample_id (our IDs have the format of "group_subject_sample number"),	subject (subject index),	group (N, P, M, etc),	match_status (whether or not there is a matched sample),	mapped (uniquely mapped reads from STAR)
# crc_matched_patients_read_info.txt is an example of our data, and is available at https://github.com/ChrisMaherLab/TMECircDB/sample_files
group.file = 'crc_matched_patients_read_info.txt';
m = read.table(group.file, header=T, stringsAsFactors=F, sep='\t', quote = '');

## Running the NNLS model

# Expression matrix, every gene per row, every sample per column
# crc_matched_patients_linear_tpm_mixture.txt is an example of our data generated by TMECircDB_featureCounts_sum.r, and is available at https://github.com/ChrisMaherLab/TMECircDB/sample_files
expression_all <- read.table("crc_matched_patients_linear_tpm_mixture.txt",header=T,sep='\t',stringsAsFactors = F);
expression_all <- subset(expression_all,expression_all$symbol!="Unknown");
expression_all <- subset(expression_all,expression_all$symbol!="NotAvail");
expression_all$symbol <- make.unique(expression_all$symbol);

expression_all <- expression_all[,c(1,1+order(colnames(expression_all)[2:31]))]

# Cell type composition matrix, every sample per row, every cell type per column
# CIBERSORT_composition_all_samples.txt is an example of our data generated by CIBERSORT, and is available at https://github.com/ChrisMaherLab/TMECircDB/sample_files
cibersort_all <- read.table("CIBERSORT_composition_all_samples.txt",header=T,sep='\t',stringsAsFactors = F);

colnames(cibersort_all) <- gsub("\\.", " ", colnames(cibersort_all));   
colnames(cibersort_all)[1] <- c("Input.Sample");
cibersort_all <- cibersort_all[,1:7];

rownames(cibersort_all) <- cibersort_all[,"Input.Sample"];
cibersort_all <- cibersort_all[,-1];
cibersort_all <- cibersort_all[ colnames(expression_all[2:31]), ];
cibersort_all <- cibersort_all[, order(colnames(cibersort_all)) ];


output_df <- data.frame(expression_all[,"symbol"]);
output_df[,paste0(colnames(cibersort_all),"_coeff")] <- NA;
output_df[,"PVal"] <- NA;
output_df[,"RSquared"] <- NA;
colnames(output_df)[1] <- "gene";


nnls_cibersort <- function(gene)
{
  print(paste0("Running NNLS for gene: ",gene));
  
  A<- as.matrix(cibersort_all);
  B<- as.numeric(expression_all[expression_all$symbol==gene,2:31]);
  
  nnls_test <- nnls(A,B);
  
  coef_test <- coef(nnls_test);
  pred_test <- as.vector(coef_test%*%t(A));
  
  lm_dummy <- lm(B~pred_test - 1);
  
  output_Coeff <- nnls_test$x;
  print("get coeff done");
  output_pvalue <- summary(lm_dummy)[["coefficients"]][1,"Pr(>|t|)"];
  print("get pvalue done");
  outout_rsquared <- summary(lm_dummy)[["r.squared"]];
  output <- c(output_Coeff,output_pvalue,outout_rsquared);
  print("done");
  return(output)
};

output_df[,2:9] <-apply(sapply(output_df$gene,nnls_cibersort),1,t);

output_df$"no_cell_types_with_positive_coefficient" <- rowSums(output_df[,grepl('_coeff', colnames(output_df))]>0,na.rm=T);

output_df <-as.matrix(output_df);

write.table(output_df,"linear_gene_nnls_result.txt",quote=F,sep="\t",col.names=T,row.names=F)

## Benchmark NNLS model results per sample
# Read the output file generated in the step above and make into a matrix
pred_matrix <- read.table("linear_gene_nnls_result.txt",header=T,sep='\t',stringsAsFactors = F);
rownames(pred_matrix) <- pred_matrix$gene;
pred_matrix <- pred_matrix[2:7];
pred_matrix <- as.matrix(apply(pred_matrix, 2, as.numeric));

# Transpose cell type composition matrix
cibersort_matrix <- t(cibersort_all);
cibersort_matrix <- as.matrix(apply(cibersort_matrix, 2, as.numeric));

# Matrix multiplication to make "modeled" expression for all samples
matrix_multiplication <- data.frame(pred_matrix %*% cibersort_matrix);

# Load pred_matrix again to get the row names - the row names and column names have to be consistent
pred_matrix <- read.table("linear_gene_nnls_result.txt",header=T,sep='\t',stringsAsFactors = F);
rownames(matrix_multiplication) <- pred_matrix$gene;
colnames(matrix_multiplication) <- gsub("^X","", colnames(matrix_multiplication));
colnames(matrix_multiplication) <- gsub("\\.","-", colnames(matrix_multiplication));

rownames(expression_all) <- expression_all$symbol;
expression_all <- expression_all[,-1];
expression_all <- subset(expression_all, rownames(expression_all) %in% rownames(matrix_multiplication));

matrix_multiplication <- matrix_multiplication[rownames(expression_all),colnames(expression_all)];

cor_by_sample <- data.frame();

#For each samples run cor.test between modeled and ground truth expression
for (i in 1:30)
{
  test <- cor.test(as.vector(expression_all[,i]), 
                   as.vector(matrix_multiplication[,i]));
  cor_by_sample["t-statistic",i] <- as.numeric(test$statistic);
  cor_by_sample["df",i] <- as.numeric(test$parameter);
  cor_by_sample["p_value",i] <- as.numeric(test$p.value);
  cor_by_sample["cor_estimate",i] <- as.numeric(test$estimate);
  cor_by_sample["ci_95_low",i] <- as.numeric(test$conf.int[1]);
  cor_by_sample["ci_95_high",i] <- as.numeric(test$conf.int[2])
}  
colnames(cor_by_sample) <- colnames(matrix_multiplication);
cor_by_sample <- data.frame(t(cor_by_sample));
cor_by_sample$sample_id <- rownames(cor_by_sample);

cor_by_sample$sample_id <- factor(cor_by_sample$sample_id,
                                  levels = cor_by_sample$sample_id[order(cor_by_sample$cor_estimate,decreasing = T)]);


write.table(cor_by_sample,"linear_gene_nnls_corr_by_sample.txt",quote=F,sep="\t",col.names=T,row.names=F)
